version: '3.7'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './:/opt/app'
      - 'app_vendor:/opt/app/vendor'
      - 'app_jwt:/opt/app/config/jwt'
    depends_on:
      - db
  server:
    image: nginx:stable-alpine
    volumes:
      - './public/:/opt/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - php

volumes:
  postgres_data:
  app_vendor:
  app_jwt: